#+TITLE: NixOS Mobile Tutorial for OnePlus 6T (fajita)
#+AUTHOR: %?
#+DATE: 2026
#+OPTIONS: toc:t num:t
#+PROPERTY: header-args:sh :session *nixos-mobile*

* Overview

This tutorial guides you through installing NixOS Mobile on a OnePlus 6T (fajita) device. The process involves building a minimal base image using the local.nix file (with fixes to make it build on x86 machines), flashing it to your device, then rebuilding on the phone itself (aarch64) with the full configuration.nix and flake method we're all used to in the NixOS ecosystem.

video tutorial; https://youtu.be/yxfDNqZ9WTM

* Clone Your Configuration Repository

First, clone or download this phoneputer repository to get you started with a minimal config to build:

#+begin_src sh
git clone https://github.com/rinnvxv/phoneputer.git
cd phoneputer
#+end_src

* Build Flashable Images

We will import the official mobile-nixos repo to build from. It will be a folder `mobile-nixos` under our phoneputer project directory. After building, we can delete it as it is only needed to build our base image for one-time use:

#+begin_src sh
git clone https://github.com/mobile-nixos/mobile-nixos.git
cd mobile-nixos
cp ../local.nix .
nix-build --argstr device oneplus-fajita -A outputs.android-fastboot-images --impure
#+end_src

* Prepare the Phone

** Update OxygenOS
1. Update OxygenOS to the latest official version
2. Remove all Google accounts to avoid FRP (Factory Reset Protection) blocks

** Enable Developer Options
1. Go to Settings → About Phone
2. Tap "Build Number" 7 times
3. Go back to Settings → Developer Options
4. Enable "USB Debugging"
5. Enable "OEM Unlocking"

** Unlock the Bootloader

Open a nix-shell with Android tools:

#+begin_src sh
nix-shell -p adb-sync android-tools
#+end_src

Check device connection:

#+begin_src sh
adb devices
#+end_src

Reboot to bootloader:

#+begin_src sh
adb -d reboot bootloader
#+end_src

Unlock bootloader (this will erase all data!):

#+begin_src sh
fastboot oem unlock
#+end_src

⚠️ **Warning**: Unlocking the bootloader will erase all data on your device!

** Copy Partitions (A/B Safety Trick)

In some cases, the inactive slot can be unpopulated or contain much older firmware than the active slot, leading to various issues including a potential hard-brick. We can ensure none of that will happen by copying the contents of the active slot to the inactive slot.

To do this, sideload the copy-partitions-20220613-signed.zip package:

1. On the device, select "Apply Update", then "Apply from ADB" to begin sideload
2. On the host machine, download and sideload the package:

#+begin_src sh
wget https://mirrorbits.lineageos.org/tools/copy-partitions-20220613-signed.zip
adb -d sideload copy-partitions-20220613-signed.zip
#+end_src

Now reboot to recovery by tapping "Advanced", then "Reboot to recovery".

** Prepare for Mainline

This assumes the phone will only run SDM845 mainline images. You will need to erase the dtbo partitions for both slots:

#+begin_src sh
fastboot erase dtbo_a
#+end_src

#+begin_src sh
fastboot erase dtbo_b
#+end_src

* Flash Images to Device

Flash the critical partitions:

#+begin_src sh
./result/flash-critical.sh
#+end_src

Flash system image:

#+begin_src sh
fastboot flash userdata system.img
#+end_src

⚠️ **Note**: If the phone isn't recognized, try connecting it *after* booting into fastboot mode.

* First Boot and Configuration

** SSH into the Phone

NixOS Mobile provides SSH access because we set it up in the local.nix base configuration we've built. Connect to the device:

#+begin_src sh
ssh root@-localip-
#+end_src

** Connect network via Computer

Rebuilding with the full flake requires internet access on thephone.
Since it's only connected via USB, we share the PC's connection over the USB link (NAT).

On PC
#+begin_src sh
ip a
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -o wlp0s20f3 -j MASQUERADE
sudo iptables -A FORWARD -i enp0s20f0u3 -o wlp0s20f3 -j ACCEPT
sudo iptables -A FORWARD -i wlp0s20f3 -o enp0s20f0u3 -m state --state RELATED,ESTABLISHED -j ACCEPT
#+end_src

On Phone
#+begin_src sh
ip route add default via 172.16.42.2
ping -c 3 8.8.8.8
#+end_src

If resolv.conf isn't blank
#+begin_src sh
cat /etc/resolv.conf
echo "nameserver 8.8.8.8" > /etc/resolv.conf
#+end_src

** Clone Your Configuration Repository

Once connected to the device we will rebuild without using the local.nix but like we're used to on a normal NixOS flake install. Adjust the configuration.nix to your liking, but I would suggest building the included one first. It will boot you into GNOME:

#+begin_src sh
git clone https://github.com/rinnvxv/phoneputer.git
cd phoneputer
#+end_src

** Rebuild with Your Flake Configuration

If the phone's USB interface uses a larger MTU than the shared path can handle, large downloads/builds will hang partway through.
Lowering MTU on both ends fixes this:

On PC
#+begin_src sh
sudo ip link set enp0s20f0u3 mtu 1400
#+end_src

On Phone
#+begin_src sh
ip link set usb0 mtu 1400
nixos-rebuild switch --flake .#phoneputer
#+end_src

* What's Next?

After the rebuild completes, your OnePlus 6 will have:
- GNOME desktop environment (with bloat removed)
- SSH access for remote development
- Your custom package selection
- Full NixOS declarative configuration

You can now:
- Customize your configuration.nix further
- Add more packages or services
- Rebuild anytime with `nixos-rebuild switch --flake .#phoneputer`
- Use the device as a full Linux development environment

* 4G / LTE Support

Once you have the base install working, check out the [[https://github.com/mwlaboratories/phoneputer/tree/4g-testing][4g-testing branch]] for a follow-up tutorial that gets cellular connectivity working. It uses a [[https://github.com/mwlaboratories/mobile-nixos/tree/sdm845-bleeding-edge][fork of mobile-nixos]] with an upgraded kernel (6.19) and critical module fixes. 4G, frontal camera, and more are all functional.

* Resources

- [[https://github.com/mwlaboratories/phoneputer/tree/4g-testing][4G Tutorial (4g-testing branch)]]
- [[https://github.com/mwlaboratories/mobile-nixos/tree/sdm845-bleeding-edge][mobile-nixos fork (sdm845-bleeding-edge)]]
- [[https://mobile.nixos.org/][NixOS Mobile Documentation]]
- [[https://github.com/mobile-nixos/mobile-nixos][Mobile NixOS GitHub]]
- [[https://github.com/mobile-nixos/mobile-nixos/issues][Report Issues]]
